replicaCount: 3
image:
  repository: michaltrmac/upload-app
  tag: 1.5.0
service:
  type: ClusterIP
  port: 9080
  targetPort: 9080
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: uploadapp.mydomain.local
      paths:
        - path: /
          pathType: ImplementationSpecific
appbackendDb:
  user: mongoroot
  password: mongotest
mongodb:
  service:
    type: ClusterIP
  persistence:
    enabled: false
  auth:
    rootUser: mongoroot
    rootPassword: mongotest
    ## Tipy pre vase zadanie semestralnej prace:
    # 1. zakomentujte si sekciu vyssie (auth a rootUser a rootPassword)
    # 2. odkomentujte si sekciu nizsie a riadte sa pokynmi v komentaroch
    #initdbScripts:
    #  init_script.js: |
    #  # Sem vlozite obsah init skriptu, ktory mate odkazany v zadani.
    #  # Vsimnite si, ze v init skripte sa vytvara databaza s nazvom "platformsdb".
    #  # Tzn. davajte si pozor na connection string, v zadani mate hint: mongodb://appbackend-mongodb:27017/dynamicky_nazov_db ,
    #  # takze ten dynamicky nazov je databaza, ktoru vytvarate v init skripte.
    #  # Pozor na spravne YAML formatovanie!
